# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

samples: config/samples.tsv
wkdir: /panfs/home/yang4414/li002252/project/tools/wkdir/
resultdir: /panfs/home/yang4414/li002252/project/tools/wkdir/
gff: /panfs/home/yang4414/li002252/project/tools/wkdir/genome/test2.sort.gff3
gtf: /panfs/home/yang4414/li002252/project/tools/wkdir/genome/Homo_sapiens.GRCh38.103.chr.gtf

simulator:
  outname: 2021-07-08-11:39:11_maxGenes2_SeqDepth2e+06_errRate0.001_readlen50_multiEventsPerExonFALSE_probsAsFreqFALSE
  outdir: /panfs/home/yang4414/li002252/project/tools/simulate/out/
  chrom: 1

fastp:
  qualified_quality_phred: 20

rmats:
  b1: /panfs/home/yang4414/li002252/project/tools/rmats_test/samples.txt
  output:  rmats/output
  nthreads: 8

majiq:
  lang: /atavium/home/yang4414/li002252/miniconda3/envs/majiq/bin/python
  script: /atavium/home/yang4414/li002252/miniconda3/envs/majiq/lib/python3.6/site-packages/majiq/run_majiq.py
  configdir: /panfs/home/yang4414/li002252/project/tools/majiq_test

spladder:

whippet:
  scriptdir: /panfs/home/yang4414/li002252/project/tools/Whippet.jl/bin/
